POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ld0B0ZXN0LmNvbSIsImV4cCI6MTczMzM4MTA2OCwidXNlcklkIjoyfQ.9GCUdHuYJNWLr3F1okqKeQeX4tixivQCQvObcmCYzOs

{
    "name": "test event 5 ",
    "description": "another test 5 event description",
    "location": "test location",
    "dateTime": "2025-02-01T15:30:00.000Z"
}