POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5ldzJAdGVzdC5jb20iLCJleHAiOjE3MzMzODQ2MzUsInVzZXJJZCI6Mn0.Up7lTxrKGpG0UI7PL6mlco3Ic60JxxN89tKSRpOWWmQ

{
    "name": "test event 5 ",
    "description": "another test 5 event description",
    "location": "test location",
    "dateTime": "2025-02-01T15:30:00.000Z"
}