PUT http://localhost:8080/events/adsd
content-type: application/json

{
    "name" : "Updated test event",
    "description" : "An updated test event",
    "location" : "Updated test location",
    "dateTime" : "2025-01-06T15:30:00.000Z"
}